# Generated by Django 2.2.12 on 2024-12-19 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentreponse',
            options={'verbose_name': 'Student Response', 'verbose_name_plural': 'Student Responses'},
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='is_True',
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='reponse',
        ),
        migrations.AddField(
            model_name='studentreponse',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentreponse',
            name='response_text',
            field=models.TextField(default=datetime.datetime(2024, 12, 19, 15, 38, 22, 218070, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student.Student'),
        ),
    ]
