# Generated by Django 2.2.12 on 2024-12-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20241227_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reponse',
            options={'verbose_name': 'Reponse', 'verbose_name_plural': 'Reponses'},
        ),
        migrations.AddField(
            model_name='reponse',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
