# Generated by Django 2.2.12 on 2024-12-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20241219_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectationmatiere',
            options={'verbose_name': 'Affectation de Matière', 'verbose_name_plural': 'Affectations de Matières'},
        ),
        migrations.AlterField(
            model_name='affectationmatiere',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='instructor.Instructor'),
        ),
        migrations.AlterField(
            model_name='affectationmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='school.Matiere'),
        ),
    ]
