# Generated by Django 2.2.12 on 2024-12-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20241221_1235'),
        ('instructor', '0004_auto_20241220_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='school.Matiere'),
        ),
    ]
